### ISSUE TITLE
Add TOGGLE

### ISSUE THREAD

**Issue by GaupeLnx** [viralanomaly/CramObjectives#1]
Hi, Thank you very much for this simple addon!  One request. Could you change it so its has also the option /cram toggle
i changed it in the LUA myself but would be nice if it got official :-)  here is my changed code

`        
local CRAM = "cram"
local HIDE = "hide"
local SHOW = "show"
local TOGGLE = "toggle"

CramObjectives = LibStub("AceAddon-3.0"):NewAddon("CramObjectives", "AceConsole-3.0", "AceEvent-3.0", "AceHook-3.0")
CO = CramObjectives
OTF = ObjectiveTrackerFrame

function CO:OnInitialize()
    CO:Print("OnInitialize")
    CODB = CODB or {}
    if CODB.hide == nil then
        CODB.hide = true
    end

    CO:RegisterChatCommand("ram", "SlashCommand")
    CO:RegisterChatCommand("cram", "SlashCommand")
end

function CO:HideTrackerIfEnabled()
    local zone = GetZoneText()

    if CODB.hide == true then
        OTF:Hide()
    end
end

function SetupHooks()
    CO:HookScript(OTF, "OnShow", "HideTrackerIfEnabled")
end

function CO:OnEnable()
    CO:Print("OnEnable")

    if CODB.hide == true then
        SetupHooks()
        OTF:Hide()
    end

end

-- Configure slash commands for enable and disable of the printing
function CO:SlashCommand(msg)
    local cmd1 = strsplit(" ", msg)

    if #cmd1 > 0 then
        cmd1 = strlower(cmd1)

        if cmd1 == CRAM or cmd1 == HIDE then
            if CODB.hide == false then
                CODB.hide = true
                OTF:Hide()
                SetupHooks()
            elseif OTF.IsVisible then
                OTF:Hide()
            else
                CO:Print("Already hidden")
            end
        elseif cmd1 == SHOW then
            if CODB.hide == true then
                CODB.hide = false
                OTF:Show()
                CO:UnhookAll()
            elseif not OTF.IsVisible then
                OTF:Show()
            else
                CO:Print("Already visible")
            end
        elseif cmd1 == TOGGLE then
            if CODB.hide == true then
                CODB.hide = false
                OTF:Show()
                CO:UnhookAll()
            elseif CODB.hide == false then
                CODB.hide = true
                OTF:Hide()
                SetupHooks()
            end
        end
    else
        CO:Print("Enter a command: /cram "..HIDE.." or /cram "..SHOW.." or /cram "..TOGGLE )
    end
end

`

**Comment by viralanomaly** [comment]
Sorry, I forgot to check in over here.  Yeah, I can look at adding that next week.

**Comment by viralanomaly** [comment]
I might change it so toggle is the default behavior.  TBD.

**Comment by GaupeLnx** [comment]
Good idea :-) and thanx  for publishing this small but very convenient addon

**Comment by viralanomaly** [comment]
I had an unexpected family emergency, but I'll be working on this today.
